class RegistrationErrorItem {
  String? fullName;
  String? phoneNumber;
  String? age;
  String? gender;
  String? language;
  String? nativePlaceState;
  String? nativePlaceDistrict;
  String? mostTimeSpend;
  String? highestQualification;
  String? jobType;
  String? occupation;
}

class RegistrationItem {
  String? fullName;
  String? phoneNumber;
  int? age;
  Gender? gender;
  Language? language;
  String? nativePlaceState;
  String? nativePlaceDistrict;
  MostTimeSpend? mostTimeSpend;
  HighestQualification? highestQualification;
  JobType? jobType;
  String? occupation;
  bool consentFormAccepted = false;

  void setAge(String? value) {
    age = int.parse(value!);
  }

  void setGender(String? value) {
    if (value == null) {
      gender = null;
    }
    gender = Gender.values.firstWhere((g) => g.toString() == value!);
  }

  void setLanguage(String? value) {
    if (value == null) {
      language = null;
    }
    language = Language.values.firstWhere((l) => l.toString() == value!);
  }

  void setMostTimeSpend(String? value) {
    if (value == null) {
      mostTimeSpend = null;
    }
    mostTimeSpend =
        MostTimeSpend.values.firstWhere((m) => m.toString() == value!);
  }

  void setHighestQualification(String? value) {
    if (value == null) {
      highestQualification = null;
    }
    highestQualification =
        HighestQualification.values.firstWhere((h) => h.toString() == value!);
  }

  void setJobType(String? value) {
    if (value == null) {
      jobType = null;
    }
    jobType = JobType.values.firstWhere((j) => j.toString() == value!);
  }

  Map<String, dynamic> getUserMap() {
    Map<String, dynamic> userJson = <String, dynamic>{};
    userJson['full_name'] = fullName;
    userJson['phone_number'] = phoneNumber;
    userJson['language'] = language?.name;
    userJson['age'] = age;
    userJson['most_time_spend'] = mostTimeSpend?.name;
    userJson['occupation'] = occupation;
    userJson['gender'] = gender?.name;
    userJson['native_place_state'] = nativePlaceState;
    userJson['native_place_district'] = nativePlaceDistrict;
    userJson['job_type'] = jobType?.name;
    userJson['highest_qualification'] = highestQualification?.name;
    return userJson;
  }
}

class RegistrationResponse {
  final int responseCode;
  final String message;
  final Map<String, dynamic> details;

  const RegistrationResponse(
      {required this.responseCode,
      required this.message,
      required this.details});

  const RegistrationResponse.success(Map<String, dynamic>? details)
      : responseCode = 200,
        message = "",
        details = details ?? const {};

  const RegistrationResponse.tryAgain()
      : responseCode = 502,
        message = "Please try again after some time.",
        details = const {};

  RegistrationResponse.badRequst(this.message)
      : responseCode = 400,
        details = const {};
}

enum Gender { male, female, other }

Map<Gender, String> gender = {
  Gender.male: "Male",
  Gender.female: "Female",
  Gender.other: "Other"
};

enum MostTimeSpend { city, big_town, small_town, village }

Map<MostTimeSpend, String> mostTimeSpend = {
  MostTimeSpend.city: "City",
  MostTimeSpend.big_town: "Big Town",
  MostTimeSpend.small_town: "Small Town",
  MostTimeSpend.village: "Village"
};

enum JobType {
  blue_collar,
  white_collar,
  student,
  unemployed,
}

Map<JobType, String> jobType = {
  JobType.blue_collar: "Blue Collar",
  JobType.white_collar: "White Collar",
  JobType.student: "Student",
  JobType.unemployed: "Unemployed",
};

enum HighestQualification {
  no_schooling,
  high_school,
  senior_high_school,
  diploma,
  ug,
  graduate,
  post_graduate,
  doctoral,
}

Map<HighestQualification, String> highestQualification = {
  HighestQualification.no_schooling: "No Schooling",
  HighestQualification.high_school: "Higher Secondary Level at School (10th)",
  HighestQualification.senior_high_school:
      "Senior Secondary Level at School (10+2)",
  HighestQualification.diploma: "Diploma Holder",
  HighestQualification.ug: "Under Graduate Student",
  HighestQualification.graduate: "Graduate",
  HighestQualification.post_graduate: "Post Graduate",
  HighestQualification.doctoral: "Doctoral (PhD) or higher level",
};

enum Language {
  punjabi,
  urdu,
  sindhi,
  manipuri,
  dogri,
  bodo,
  maithili,
  sanskrit,
  kashmiri,
  nepali,
  telugu,
  assamese,
  bengali,
  odia,
  gujarati,
  marathi,
  kannada,
  konkani,
  hindi,
  malayalam,
  santali,
  tamil,
}

Map<Language, String> language = {
  Language.punjabi: "Punjabi",
  Language.urdu: "Urdu",
  Language.sindhi: "Sindhi",
  Language.manipuri: "Manipuri",
  Language.dogri: "Dogri",
  Language.bodo: "Bodo",
  Language.maithili: "Maithili",
  Language.sanskrit: "Sanskrit",
  Language.kashmiri: "Kashmiri",
  Language.nepali: "Nepali",
  Language.telugu: "Telugu",
  Language.assamese: "Assamese",
  Language.bengali: "Bengali",
  Language.odia: "Odia",
  Language.gujarati: "Gujarati",
  Language.marathi: "Marathi",
  Language.kannada: "Kannada",
  Language.konkani: "Konkani",
  Language.hindi: "Hindi",
  Language.malayalam: "Malayalam",
  Language.santali: "Santali",
  Language.tamil: "Tamil",
};

class Location {
  final String name;
  final Map<String, String> district;

  const Location(this.name, this.district);
}

const Map<String, Location> locations = {
  "andaman_nicobar": Location("Andaman Nicobar", {
    "nicobar": "Nicobar",
    "north_middle_andaman": "North Middle Andaman",
    "south_andaman": "South Andaman",
  }),
  "andhra_pradesh": Location("Andhra Pradesh", {
    "anantapur": "Anantapur",
    "chittoor": "Chittoor",
    "east_godavari": "East Godavari",
    "alluri_sitarama_raju": "Alluri Sitarama Raju",
    "anakapalli": "Anakapalli",
    "annamaya": "Annamaya",
    "bapatla": "Bapatla",
    "eluru": "Eluru",
    "guntur": "Guntur",
    "kadapa": "Kadapa",
    "kakinada": "Kakinada",
    "konaseema": "Konaseema",
    "krishna": "Krishna",
    "kurnool": "Kurnool",
    "manyam": "Manyam",
    "n_t_rama_rao": "N T Rama Rao",
    "nandyal": "Nandyal",
    "nellore": "Nellore",
    "palnadu": "Palnadu",
    "prakasam": "Prakasam",
    "sri_balaji": "Sri Balaji",
    "sri_satya_sai": "Sri Satya Sai",
    "srikakulam": "Srikakulam",
    "visakhapatnam": "Visakhapatnam",
    "vizianagaram": "Vizianagaram",
    "west_godavari": "West Godavari",
  }),
  "arunachal_pradesh": Location("Arunachal Pradesh", {
    "anjaw": "Anjaw",
    "central_siang": "Central Siang",
    "changlang": "Changlang",
    "dibang_valley": "Dibang Valley",
    "east_kameng": "East Kameng",
    "east_siang": "East Siang",
    "kamle": "Kamle",
    "kra_daadi": "Kra Daadi",
    "kurung_kumey": "Kurung Kumey",
    "lepa_rada": "Lepa Rada",
    "lohit": "Lohit",
    "longding": "Longding",
    "lower_dibang_valley": "Lower Dibang Valley",
    "lower_siang": "Lower Siang",
    "lower_subansiri": "Lower Subansiri",
    "namsai": "Namsai",
    "pakke_kessang": "Pakke Kessang",
    "papum_pare": "Papum Pare",
    "shi_yomi": "Shi Yomi",
    "tawang": "Tawang",
    "tirap": "Tirap",
    "upper_siang": "Upper Siang",
    "upper_subansiri": "Upper Subansiri",
    "west_kameng": "West Kameng",
    "west_siang": "West Siang",
  }),
  "assam": Location("Assam", {
    "bajali": "Bajali",
    "baksa": "Baksa",
    "barpeta": "Barpeta",
    "biswanath": "Biswanath",
    "bongaigaon": "Bongaigaon",
    "cachar": "Cachar",
    "charaideo": "Charaideo",
    "chirang": "Chirang",
    "darrang": "Darrang",
    "dhemaji": "Dhemaji",
    "dhubri": "Dhubri",
    "dibrugarh": "Dibrugarh",
    "dima_hasao": "Dima Hasao",
    "goalpara": "Goalpara",
    "golaghat": "Golaghat",
    "hailakandi": "Hailakandi",
    "hojai": "Hojai",
    "jorhat": "Jorhat",
    "kamrup": "Kamrup",
    "kamrup_metropolitan": "Kamrup Metropolitan",
    "karbi_anglong": "Karbi Anglong",
    "karimganj": "Karimganj",
    "kokrajhar": "Kokrajhar",
    "lakhimpur": "Lakhimpur",
    "majuli": "Majuli",
    "morigaon": "Morigaon",
    "nagaon": "Nagaon",
    "nalbari": "Nalbari",
    "sivasagar": "Sivasagar",
    "sonitpur": "Sonitpur",
    "south_salmara-mankachar": "South Salmara-Mankachar",
    "tamulpur": "Tamulpur",
    "tinsukia": "Tinsukia",
    "udalguri": "Udalguri",
    "west_karbi_anglong": "West Karbi Anglong",
  }),
  "bihar": Location("Bihar", {
    "araria": "Araria",
    "arwal": "Arwal",
    "aurangabad": "Aurangabad",
    "banka": "Banka",
    "begusarai": "Begusarai",
    "bhagalpur": "Bhagalpur",
    "bhojpur": "Bhojpur",
    "buxar": "Buxar",
    "darbhanga": "Darbhanga",
    "east_champaran": "East Champaran",
    "gaya": "Gaya",
    "gopalganj": "Gopalganj",
    "jamui": "Jamui",
    "jehanabad": "Jehanabad",
    "kaimur": "Kaimur",
    "katihar": "Katihar",
    "khagaria": "Khagaria",
    "kishanganj": "Kishanganj",
    "lakhisarai": "Lakhisarai",
    "madhepura": "Madhepura",
    "madhubani": "Madhubani",
    "munger": "Munger",
    "muzaffarpur": "Muzaffarpur",
    "nalanda": "Nalanda",
    "nawada": "Nawada",
    "patna": "Patna",
    "purnia": "Purnia",
    "rohtas": "Rohtas",
    "saharsa": "Saharsa",
    "samastipur": "Samastipur",
    "saran": "Saran",
    "sheikhpura": "Sheikhpura",
    "sheohar": "Sheohar",
    "sitamarhi": "Sitamarhi",
    "siwan": "Siwan",
    "supaul": "Supaul",
    "vaishali": "Vaishali",
    "west_champaran": "West Champaran",
  }),
  "chandigarh": Location("Chandigarh", {
    "chandigarh": "Chandigarh",
  }),
  "chhattisgarh": Location("Chhattisgarh", {
    "balod": "Balod",
    "baloda_bazar": "Baloda Bazar",
    "balrampur": "Balrampur",
    "bastar": "Bastar",
    "bemetara": "Bemetara",
    "bijapur": "Bijapur",
    "bilaspur": "Bilaspur",
    "dantewada": "Dantewada",
    "dhamtari": "Dhamtari",
    "durg": "Durg",
    "gariaband": "Gariaband",
    "gaurela_pendra_marwahi": "Gaurela Pendra Marwahi",
    "janjgir_champa": "Janjgir Champa",
    "jashpur": "Jashpur",
    "kabirdham": "Kabirdham",
    "kanker": "Kanker",
    "khairagarh": "Khairagarh",
    "kondagaon": "Kondagaon",
    "korba": "Korba",
    "koriya": "Koriya",
    "mahasamund": "Mahasamund",
    "manendragarh": "Manendragarh",
    "mohla_manpur": "Mohla Manpur",
    "mungeli": "Mungeli",
    "narayanpur": "Narayanpur",
    "raigarh": "Raigarh",
    "raipur": "Raipur",
    "rajnandgaon": "Rajnandgaon",
    "sakti": "Sakti",
    "sarangarh_bilaigarh": "Sarangarh Bilaigarh",
    "sukma": "Sukma",
    "surajpur": "Surajpur",
    "surguja": "Surguja",
  }),
  "dadra_and_nagar_haveli_and_daman_and_diu":
      Location("Dadra and Nagar Haveli and Daman and Diu", {
    "dadra_and_nagar_haveli": "Dadra and Nagar Haveli",
    "daman": "Daman",
    "diu": "Diu",
  }),
  "delhi": Location("Delhi", {
    "central_delhi": "Central Delhi",
    "east_delhi": "East Delhi",
    "new_delhi": "New Delhi",
    "north_delhi": "North Delhi",
    "north_east_delhi": "North East Delhi",
    "north_west_delhi": "North West Delhi",
    "shahdara": "Shahdara",
    "south_delhi": "South Delhi",
    "south_east_delhi": "South East Delhi",
    "south_west_delhi": "South West Delhi",
    "west_delhi": "West Delhi",
  }),
  "goa": Location("Goa", {
    "north_goa": "North Goa",
    "south_goa": "South Goa",
  }),
  "sikkim": Location("Sikkim", {
    "gyalshing": "Gyalshing",
    "namchi": "Namchi",
    "pakyong": "Pakyong",
    "soreng": "Soreng",
    "mangan": "Mangan",
    "gangtok": "Gangtok",
  }),
  "gujarat": Location("Gujarat", {
    "ahmedabad": "Ahmedabad",
    "amreli": "Amreli",
    "anand": "Anand",
    "aravalli": "Aravalli",
    "banaskantha": "Banaskantha",
    "bharuch": "Bharuch",
    "bhavnagar": "Bhavnagar",
    "botad": "Botad",
    "chhota_udaipur": "Chhota Udaipur",
    "dahod": "Dahod",
    "dang": "Dang",
    "devbhoomi_dwarka": "Devbhoomi Dwarka",
    "gandhinagar": "Gandhinagar",
    "gir_somnath": "Gir Somnath",
    "jamnagar": "Jamnagar",
    "junagadh": "Junagadh",
    "kheda": "Kheda",
    "kutch": "Kutch",
    "mahisagar": "Mahisagar",
    "mehsana": "Mehsana",
    "morbi": "Morbi",
    "narmada": "Narmada",
    "navsari": "Navsari",
    "panchmahal": "Panchmahal",
    "patan": "Patan",
    "porbandar": "Porbandar",
    "rajkot": "Rajkot",
    "sabarkantha": "Sabarkantha",
    "surat": "Surat",
    "surendranagar": "Surendranagar",
    "tapi": "Tapi",
    "vadodara": "Vadodara",
    "valsad": "Valsad",
  }),
  "haryana": Location("Haryana", {
    "ambala": "Ambala",
    "bhiwani": "Bhiwani",
    "charkhi_dadri": "Charkhi Dadri",
    "faridabad": "Faridabad",
    "fatehabad": "Fatehabad",
    "gurugram": "Gurugram",
    "hisar": "Hisar",
    "jhajjar": "Jhajjar",
    "jind": "Jind",
    "kaithal": "Kaithal",
    "karnal": "Karnal",
    "kurukshetra": "Kurukshetra",
    "mahendragarh": "Mahendragarh",
    "mewat": "Mewat",
    "palwal": "Palwal",
    "panchkula": "Panchkula",
    "panipat": "Panipat",
    "rewari": "Rewari",
    "rohtak": "Rohtak",
    "sirsa": "Sirsa",
    "sonipat": "Sonipat",
    "yamunanagar": "Yamunanagar",
  }),
  "himachal_pradesh": Location("Himachal Pradesh", {
    "bilaspur": "Bilaspur",
    "chamba": "Chamba",
    "hamirpur": "Hamirpur",
    "kangra": "Kangra",
    "kinnaur": "Kinnaur",
    "kullu": "Kullu",
    "lahaul_spiti": "Lahaul Spiti",
    "mandi": "Mandi",
    "shimla": "Shimla",
    "sirmaur": "Sirmaur",
    "solan": "Solan",
    "una": "Una",
  }),
  "jammu_kashmir": Location("Jammu Kashmir", {
    "anantnag": "Anantnag",
    "bandipora": "Bandipora",
    "baramulla": "Baramulla",
    "budgam": "Budgam",
    "doda": "Doda",
    "ganderbal": "Ganderbal",
    "jammu": "Jammu",
    "kathua": "Kathua",
    "kishtwar": "Kishtwar",
    "kulgam": "Kulgam",
    "kupwara": "Kupwara",
    "poonch": "Poonch",
    "pulwama": "Pulwama",
    "rajouri": "Rajouri",
    "ramban": "Ramban",
    "reasi": "Reasi",
    "samba": "Samba",
    "shopian": "Shopian",
    "srinagar": "Srinagar",
    "udhampur": "Udhampur",
  }),
  "jharkhand": Location("Jharkhand", {
    "bokaro": "Bokaro",
    "chatra": "Chatra",
    "deoghar": "Deoghar",
    "dhanbad": "Dhanbad",
    "dumka": "Dumka",
    "east_singhbhum": "East Singhbhum",
    "garhwa": "Garhwa",
    "giridih": "Giridih",
    "godda": "Godda",
    "gumla": "Gumla",
    "hazaribagh": "Hazaribagh",
    "jamtara": "Jamtara",
    "khunti": "Khunti",
    "koderma": "Koderma",
    "latehar": "Latehar",
    "lohardaga": "Lohardaga",
    "pakur": "Pakur",
    "palamu": "Palamu",
    "ramgarh": "Ramgarh",
    "ranchi": "Ranchi",
    "sahebganj": "Sahebganj",
    "seraikela_kharsawan": "Seraikela Kharsawan",
    "simdega": "Simdega",
    "west_singhbhum": "West Singhbhum",
  }),
  "karnataka": Location("Karnataka", {
    "bagalkot": "Bagalkot",
    "bangalore_rural": "Bangalore Rural",
    "bangalore_urban": "Bangalore Urban",
    "belgaum": "Belgaum",
    "bellary": "Bellary",
    "bidar": "Bidar",
    "chamarajanagar": "Chamarajanagar",
    "chikkaballapur": "Chikkaballapur",
    "chikkamagaluru": "Chikkamagaluru",
    "chitradurga": "Chitradurga",
    "dakshina_kannada": "Dakshina Kannada",
    "davanagere": "Davanagere",
    "dharwad": "Dharwad",
    "gadag": "Gadag",
    "gulbarga": "Gulbarga",
    "hassan": "Hassan",
    "haveri": "Haveri",
    "kodagu": "Kodagu",
    "kolar": "Kolar",
    "koppal": "Koppal",
    "mandya": "Mandya",
    "mysore": "Mysore",
    "raichur": "Raichur",
    "ramanagara": "Ramanagara",
    "shimoga": "Shimoga",
    "tumkur": "Tumkur",
    "udupi": "Udupi",
    "uttara_kannada": "Uttara Kannada",
    "vijayanagara": "Vijayanagara",
    "vijayapura": "Vijayapura",
    "yadgir": "Yadgir",
  }),
  "kerala": Location("Kerala", {
    "alappuzha": "Alappuzha",
    "ernakulam": "Ernakulam",
    "idukki": "Idukki",
    "kannur": "Kannur",
    "kasaragod": "Kasaragod",
    "kollam": "Kollam",
    "kottayam": "Kottayam",
    "kozhikode": "Kozhikode",
    "malappuram": "Malappuram",
    "palakkad": "Palakkad",
    "pathanamthitta": "Pathanamthitta",
    "thiruvananthapuram": "Thiruvananthapuram",
    "thrissur": "Thrissur",
    "wayanad": "Wayanad",
  }),
  "ladakh": Location("Ladakh", {
    "kargil": "Kargil",
    "leh": "Leh",
  }),
  "lakshadweep": Location("Lakshadweep", {
    "lakshadweep": "Lakshadweep",
  }),
  "madhya_pradesh": Location("Madhya Pradesh", {
    "agar_malwa": "Agar Malwa",
    "alirajpur": "Alirajpur",
    "anuppur": "Anuppur",
    "ashoknagar": "Ashoknagar",
    "balaghat": "Balaghat",
    "barwani": "Barwani",
    "betul": "Betul",
    "bhind": "Bhind",
    "bhopal": "Bhopal",
    "burhanpur": "Burhanpur",
    "chachaura": "Chachaura",
    "chhatarpur": "Chhatarpur",
    "chhindwara": "Chhindwara",
    "damoh": "Damoh",
    "datia": "Datia",
    "dewas": "Dewas",
    "dhar": "Dhar",
    "dindori": "Dindori",
    "guna": "Guna",
    "gwalior": "Gwalior",
    "harda": "Harda",
    "hoshangabad": "Hoshangabad",
    "indore": "Indore",
    "jabalpur": "Jabalpur",
    "jhabua": "Jhabua",
    "katni": "Katni",
    "khandwa": "Khandwa",
    "khargone": "Khargone",
    "maihar": "Maihar",
    "mandla": "Mandla",
    "mandsaur": "Mandsaur",
    "morena": "Morena",
    "nagda": "Nagda",
    "narsinghpur": "Narsinghpur",
    "neemuch": "Neemuch",
    "niwari": "Niwari",
    "panna": "Panna",
    "raisen": "Raisen",
    "rajgarh": "Rajgarh",
    "ratlam": "Ratlam",
    "rewa": "Rewa",
    "sagar": "Sagar",
    "satna": "Satna",
    "sehore": "Sehore",
    "seoni": "Seoni",
    "shahdol": "Shahdol",
    "shajapur": "Shajapur",
    "sheopur": "Sheopur",
    "shivpuri": "Shivpuri",
    "sidhi": "Sidhi",
    "singrauli": "Singrauli",
    "tikamgarh": "Tikamgarh",
    "ujjain": "Ujjain",
    "umaria": "Umaria",
    "vidisha": "Vidisha",
  }),
  "maharashtra": Location("Maharashtra", {
    "ahmednagar": "Ahmednagar",
    "akola": "Akola",
    "amravati": "Amravati",
    "aurangabad": "Aurangabad",
    "beed": "Beed",
    "bhandara": "Bhandara",
    "buldhana": "Buldhana",
    "chandrapur": "Chandrapur",
    "dhule": "Dhule",
    "gadchiroli": "Gadchiroli",
    "gondia": "Gondia",
    "hingoli": "Hingoli",
    "jalgaon": "Jalgaon",
    "jalna": "Jalna",
    "kolhapur": "Kolhapur",
    "latur": "Latur",
    "mumbai_city": "Mumbai City",
    "mumbai_suburban": "Mumbai Suburban",
    "nagpur": "Nagpur",
    "nanded": "Nanded",
    "nandurbar": "Nandurbar",
    "nashik": "Nashik",
    "osmanabad": "Osmanabad",
    "palghar": "Palghar",
    "parbhani": "Parbhani",
    "pune": "Pune",
    "raigad": "Raigad",
    "ratnagiri": "Ratnagiri",
    "sangli": "Sangli",
    "satara": "Satara",
    "sindhudurg": "Sindhudurg",
    "solapur": "Solapur",
    "thane": "Thane",
    "wardha": "Wardha",
    "washim": "Washim",
    "yavatmal": "Yavatmal",
  }),
  "manipur": Location("Manipur", {
    "bishnupur": "Bishnupur",
    "chandel": "Chandel",
    "churachandpur": "Churachandpur",
    "imphal_east": "Imphal East",
    "imphal_west": "Imphal West",
    "jiribam": "Jiribam",
    "kakching": "Kakching",
    "kamjong": "Kamjong",
    "kangpokpi": "Kangpokpi",
    "noney": "Noney",
    "pherzawl": "Pherzawl",
    "senapati": "Senapati",
    "tamenglong": "Tamenglong",
    "tengnoupal": "Tengnoupal",
    "thoubal": "Thoubal",
    "ukhrul": "Ukhrul",
  }),
  "meghalaya": Location("Meghalaya", {
    "east_garo_hills": "East Garo Hills",
    "east_jaintia_hills": "East Jaintia Hills",
    "east_khasi_hills": "East Khasi Hills",
    "mairang": "Mairang",
    "north_garo_hills": "North Garo Hills",
    "ri_bhoi": "Ri Bhoi",
    "south_garo_hills": "South Garo Hills",
    "south_west_garo_hills": "South West Garo Hills",
    "south_west_khasi_hills": "South West Khasi Hills",
    "west_garo_hills": "West Garo Hills",
    "west_jaintia_hills": "West Jaintia Hills",
    "west_khasi_hills": "West Khasi Hills",
  }),
  "mizoram": Location("Mizoram", {
    "aizawl": "Aizawl",
    "champhai": "Champhai",
    "hnahthial": "Hnahthial",
    "kolasib": "Kolasib",
    "khawzawl": "Khawzawl",
    "lawngtlai": "Lawngtlai",
    "lunglei": "Lunglei",
    "mamit": "Mamit",
    "saiha": "Saiha",
    "serchhip": "Serchhip",
    "saitual": "Saitual",
  }),
  "nagaland": Location("Nagaland", {
    "chumukedima": "Chumukedima",
    "dimapur": "Dimapur",
    "kiphire": "Kiphire",
    "kohima": "Kohima",
    "longleng": "Longleng",
    "mokokchung": "Mokokchung",
    "mon": "Mon",
    "niuland": "Niuland",
    "noklak": "Noklak",
    "peren": "Peren",
    "phek": "Phek",
    "shamator": "Shamator",
    "tseminyu": "Tseminyu",
    "tuensang": "Tuensang",
    "wokha": "Wokha",
    "zunheboto": "Zunheboto",
  }),
  "odisha": Location("Odisha", {
    "angul": "Angul",
    "balangir": "Balangir",
    "balasore": "Balasore",
    "bargarh": "Bargarh",
    "bhadrak": "Bhadrak",
    "boudh": "Boudh",
    "cuttack": "Cuttack",
    "debagarh": "Debagarh",
    "dhenkanal": "Dhenkanal",
    "gajapati": "Gajapati",
    "ganjam": "Ganjam",
    "jagatsinghpur": "Jagatsinghpur",
    "jajpur": "Jajpur",
    "jharsuguda": "Jharsuguda",
    "kalahandi": "Kalahandi",
    "kandhamal": "Kandhamal",
    "kendrapara": "Kendrapara",
    "kendujhar": "Kendujhar",
    "khordha": "Khordha",
    "koraput": "Koraput",
    "malkangiri": "Malkangiri",
    "mayurbhanj": "Mayurbhanj",
    "nabarangpur": "Nabarangpur",
    "nayagarh": "Nayagarh",
    "nuapada": "Nuapada",
    "puri": "Puri",
    "rayagada": "Rayagada",
    "sambalpur": "Sambalpur",
    "subarnapur": "Subarnapur",
    "sundergarh": "Sundergarh",
  }),
  "puducherry": Location("Puducherry", {
    "karaikal": "Karaikal",
    "mahe": "Mahe",
    "puducherry": "Puducherry",
    "yanam": "Yanam",
  }),
  "punjab": Location("Punjab", {
    "amritsar": "Amritsar",
    "barnala": "Barnala",
    "bathinda": "Bathinda",
    "faridkot": "Faridkot",
    "fatehgarh_sahib": "Fatehgarh Sahib",
    "fazilka": "Fazilka",
    "firozpur": "Firozpur",
    "gurdaspur": "Gurdaspur",
    "hoshiarpur": "Hoshiarpur",
    "jalandhar": "Jalandhar",
    "kapurthala": "Kapurthala",
    "ludhiana": "Ludhiana",
    "malerkotla": "Malerkotla",
    "mansa": "Mansa",
    "moga": "Moga",
    "mohali": "Mohali",
    "muktsar": "Muktsar",
    "pathankot": "Pathankot",
    "patiala": "Patiala",
    "rupnagar": "Rupnagar",
    "sangrur": "Sangrur",
    "shaheed_bhagat_singh_nagar": "Shaheed Bhagat Singh Nagar",
    "tarn_taran": "Tarn Taran",
  }),
  "rajasthan": Location("Rajasthan", {
    "ajmer": "Ajmer",
    "alwar": "Alwar",
    "banswara": "Banswara",
    "baran": "Baran",
    "barmer": "Barmer",
    "bharatpur": "Bharatpur",
    "bhilwara": "Bhilwara",
    "bikaner": "Bikaner",
    "bundi": "Bundi",
    "chittorgarh": "Chittorgarh",
    "churu": "Churu",
    "dausa": "Dausa",
    "dholpur": "Dholpur",
    "dungarpur": "Dungarpur",
    "hanumangarh": "Hanumangarh",
    "jaipur": "Jaipur",
    "jaisalmer": "Jaisalmer",
    "jalore": "Jalore",
    "jhalawar": "Jhalawar",
    "jhunjhunu": "Jhunjhunu",
    "jodhpur": "Jodhpur",
    "karauli": "Karauli",
    "kota": "Kota",
    "nagaur": "Nagaur",
    "pali": "Pali",
    "pratapgarh": "Pratapgarh",
    "rajsamand": "Rajsamand",
    "sawai_madhopur": "Sawai Madhopur",
    "sikar": "Sikar",
    "sirohi": "Sirohi",
    "sri_ganganagar": "Sri Ganganagar",
    "tonk": "Tonk",
    "udaipur": "Udaipur",
  }),
  "tamil_nadu": Location("Tamil Nadu", {
    "ariyalur": "Ariyalur",
    "chengalpattu": "Chengalpattu",
    "chennai": "Chennai",
    "coimbatore": "Coimbatore",
    "cuddalore": "Cuddalore",
    "dharmapuri": "Dharmapuri",
    "dindigul": "Dindigul",
    "erode": "Erode",
    "kallakurichi": "Kallakurichi",
    "kanchipuram": "Kanchipuram",
    "kanyakumari": "Kanyakumari",
    "karur": "Karur",
    "krishnagiri": "Krishnagiri",
    "madurai": "Madurai",
    "mayiladuthurai": "Mayiladuthurai",
    "nagapattinam": "Nagapattinam",
    "namakkal": "Namakkal",
    "nilgiris": "Nilgiris",
    "perambalur": "Perambalur",
    "pudukkottai": "Pudukkottai",
    "ramanathapuram": "Ramanathapuram",
    "ranipet": "Ranipet",
    "salem": "Salem",
    "sivaganga": "Sivaganga",
    "tenkasi": "Tenkasi",
    "thanjavur": "Thanjavur",
    "theni": "Theni",
    "thoothukudi": "Thoothukudi",
    "tiruchirappalli": "Tiruchirappalli",
    "tirunelveli": "Tirunelveli",
    "tirupattur": "Tirupattur",
    "tiruppur": "Tiruppur",
    "tiruvallur": "Tiruvallur",
    "tiruvannamalai": "Tiruvannamalai",
    "tiruvarur": "Tiruvarur",
    "vellore": "Vellore",
    "viluppuram": "Viluppuram",
    "virudhunagar": "Virudhunagar",
  }),
  "telangana": Location("Telangana", {
    "adilabad": "Adilabad",
    "bhadradri_kothagudem": "Bhadradri Kothagudem",
    "hyderabad": "Hyderabad",
    "jagtial": "Jagtial",
    "jangaon": "Jangaon",
    "jayashankar": "Jayashankar",
    "jogulamba": "Jogulamba",
    "kamareddy": "Kamareddy",
    "karimnagar": "Karimnagar",
    "khammam": "Khammam",
    "komaram_bheem": "Komaram Bheem",
    "mahabubabad": "Mahabubabad",
    "mahbubnagar": "Mahbubnagar",
    "mancherial": "Mancherial",
    "medak": "Medak",
    "medchal": "Medchal",
    "mulugu": "Mulugu",
    "nagarkurnool": "Nagarkurnool",
    "nalgonda": "Nalgonda",
    "narayanpet": "Narayanpet",
    "nirmal": "Nirmal",
    "nizamabad": "Nizamabad",
    "peddapalli": "Peddapalli",
    "rajanna_sircilla": "Rajanna Sircilla",
    "ranga_reddy": "Ranga Reddy",
    "sangareddy": "Sangareddy",
    "siddipet": "Siddipet",
    "suryapet": "Suryapet",
    "vikarabad": "Vikarabad",
    "wanaparthy": "Wanaparthy",
    "warangal": "Warangal",
    "hanamkonda": "Hanamkonda",
    "yadadri_bhuvanagiri": "Yadadri Bhuvanagiri",
  }),
  "tripura": Location("Tripura", {
    "dhalai": "Dhalai",
    "gomati": "Gomati",
    "khowai": "Khowai",
    "north_tripura": "North Tripura",
    "sepahijala": "Sepahijala",
    "south_tripura": "South Tripura",
    "unakoti": "Unakoti",
    "west_tripura": "West Tripura",
  }),
  "uttar_pradesh": Location("Uttar Pradesh", {
    "agra": "Agra",
    "aligarh": "Aligarh",
    "ambedkar_nagar": "Ambedkar Nagar",
    "amethi": "Amethi",
    "amroha": "Amroha",
    "auraiya": "Auraiya",
    "ayodhya": "Ayodhya",
    "azamgarh": "Azamgarh",
    "baghpat": "Baghpat",
    "bahraich": "Bahraich",
    "ballia": "Ballia",
    "balrampur": "Balrampur",
    "banda": "Banda",
    "barabanki": "Barabanki",
    "bareilly": "Bareilly",
    "basti": "Basti",
    "bhadohi": "Bhadohi",
    "bijnor": "Bijnor",
    "budaun": "Budaun",
    "bulandshahr": "Bulandshahr",
    "chandauli": "Chandauli",
    "chitrakoot": "Chitrakoot",
    "deoria": "Deoria",
    "etah": "Etah",
    "etawah": "Etawah",
    "farrukhabad": "Farrukhabad",
    "fatehpur": "Fatehpur",
    "firozabad": "Firozabad",
    "gautam_buddha_nagar": "Gautam Buddha Nagar",
    "ghaziabad": "Ghaziabad",
    "ghazipur": "Ghazipur",
    "gonda": "Gonda",
    "gorakhpur": "Gorakhpur",
    "hamirpur": "Hamirpur",
    "hapur": "Hapur",
    "hardoi": "Hardoi",
    "hathras": "Hathras",
    "jalaun": "Jalaun",
    "jaunpur": "Jaunpur",
    "jhansi": "Jhansi",
    "kannauj": "Kannauj",
    "kanpur_dehat": "Kanpur Dehat",
    "kanpur_nagar": "Kanpur Nagar",
    "kasganj": "Kasganj",
    "kaushambi": "Kaushambi",
    "kheri": "Kheri",
    "kushinagar": "Kushinagar",
    "lalitpur": "Lalitpur",
    "lucknow": "Lucknow",
    "maharajganj": "Maharajganj",
    "mahoba": "Mahoba",
    "mainpuri": "Mainpuri",
    "mathura": "Mathura",
    "mau": "Mau",
    "meerut": "Meerut",
    "mirzapur": "Mirzapur",
    "moradabad": "Moradabad",
    "muzaffarnagar": "Muzaffarnagar",
    "pilibhit": "Pilibhit",
    "pratapgarh": "Pratapgarh",
    "prayagraj": "Prayagraj",
    "raebareli": "Raebareli",
    "rampur": "Rampur",
    "saharanpur": "Saharanpur",
    "sambhal": "Sambhal",
    "sant_kabir_nagar": "Sant Kabir Nagar",
    "shahjahanpur": "Shahjahanpur",
    "shamli": "Shamli",
    "shravasti": "Shravasti",
    "siddharthnagar": "Siddharthnagar",
    "sitapur": "Sitapur",
    "sonbhadra": "Sonbhadra",
    "sultanpur": "Sultanpur",
    "unnao": "Unnao",
    "varanasi": "Varanasi",
  }),
  "uttarakhand": Location("Uttarakhand", {
    "almora": "Almora",
    "bageshwar": "Bageshwar",
    "chamoli": "Chamoli",
    "champawat": "Champawat",
    "dehradun": "Dehradun",
    "haridwar": "Haridwar",
    "nainital": "Nainital",
    "pauri": "Pauri",
    "pithoragarh": "Pithoragarh",
    "rudraprayag": "Rudraprayag",
    "tehri": "Tehri",
    "udham_singh_nagar": "Udham Singh Nagar",
    "uttarkashi": "Uttarkashi",
  }),
  "west_bengal": Location("West Bengal", {
    "alipurduar": "Alipurduar",
    "bankura": "Bankura",
    "birbhum": "Birbhum",
    "cooch_behar": "Cooch Behar",
    "dakshin_dinajpur": "Dakshin Dinajpur",
    "darjeeling": "Darjeeling",
    "hooghly": "Hooghly",
    "howrah": "Howrah",
    "jalpaiguri": "Jalpaiguri",
    "jhargram": "Jhargram",
    "kalimpong": "Kalimpong",
    "kolkata": "Kolkata",
    "malda": "Malda",
    "murshidabad": "Murshidabad",
    "nadia": "Nadia",
    "north_24_parganas": "North 24 Parganas",
    "paschim_bardhaman": "Paschim Bardhaman",
    "paschim_medinipur": "Paschim Medinipur",
    "purba_bardhaman": "Purba Bardhaman",
    "purba_medinipur": "Purba Medinipur",
    "purulia": "Purulia",
    "south_24_parganas": "South 24 Parganas",
    "uttar_dinajpur": "Uttar Dinajpur",
  }),
};
