// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE-IKxyYefBE1Izt-ZhBdsngNxW2yiozQ',
    appId: '1:525231115784:web:f8187fae3c3b0d27b24bbd',
    messagingSenderId: '525231115784',
    projectId: 'karyaxplatform',
    authDomain: 'karyaxplatform.firebaseapp.com',
    storageBucket: 'karyaxplatform.firebasestorage.app',
    measurementId: 'G-RSC508ZG0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7PzufzVCwZX81ciCHQKof23ggQ0TMUTI',
    appId: '1:525231115784:android:98c99a9fad1f6633b24bbd',
    messagingSenderId: '525231115784',
    projectId: 'karyaxplatform',
    storageBucket: 'karyaxplatform.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASrxLtVFUttj2xZU60jXCob5J_hGx9x-Y',
    appId: '1:525231115784:ios:848004287ba2a4bcb24bbd',
    messagingSenderId: '525231115784',
    projectId: 'karyaxplatform',
    storageBucket: 'karyaxplatform.firebasestorage.app',
    iosBundleId: 'com.example.karyaFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASrxLtVFUttj2xZU60jXCob5J_hGx9x-Y',
    appId: '1:525231115784:ios:848004287ba2a4bcb24bbd',
    messagingSenderId: '525231115784',
    projectId: 'karyaxplatform',
    storageBucket: 'karyaxplatform.firebasestorage.app',
    iosBundleId: 'com.example.karyaFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE-IKxyYefBE1Izt-ZhBdsngNxW2yiozQ',
    appId: '1:525231115784:web:cfce50e3192632afb24bbd',
    messagingSenderId: '525231115784',
    projectId: 'karyaxplatform',
    authDomain: 'karyaxplatform.firebaseapp.com',
    storageBucket: 'karyaxplatform.firebasestorage.app',
    measurementId: 'G-WJMWHLT5KQ',
  );
}
